default_language_version:
  python: python3

repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: gui-naming-linter
        name: GUI Naming Linter
        entry: runLinter
        language: python
        types: [python]
      - id: ui-compile-check
        name: Qt UI compile check
        entry: python3 scripts/uiCompile.py --check
        language: system
        files: \.ui$
        pass_filenames: false
