"""SQLite persistence using SQLAlchemy."""

from .database import Database, DatabaseError
from .models import (
    AttributeSnapshot,
    Base,
    ImportSession,
    ObjectModelFormation,
    ObjectModelFormationInstruction,
    ObjectModelPosition,
    ObjectModelPositionInstruction,
    ObjectModelPlayer,
    ObjectModelPlayerAttribute,
    ObjectModelSquad,
    ObjectModelTactic,
    ObjectModelTransitionInstruction,
    Player,
    Squad,
    SquadClubScreenshot,
    SquadScreenshot,
    SquadTacticApplication,
    StructuredFormationSlot,
    ScreenshotDerivedTacticDefinition,
    StructuredTacticIssue,
    StructuredTeamInstruction,
    Tactic,
    TacticScreenshot,
)
from .records import (
    DeletionRecord,
    SquadCleanupRecord,
    SquadPlayerRecord,
    SquadRecord,
    TacticDetailRecord,
    TacticRecord,
)

__all__ = [
    "AttributeSnapshot",
    "Base",
    "Database",
    "DatabaseError",
    "DeletionRecord",
    "ImportSession",
    "ObjectModelFormation",
    "ObjectModelFormationInstruction",
    "ObjectModelPosition",
    "ObjectModelPositionInstruction",
    "ObjectModelPlayer",
    "ObjectModelPlayerAttribute",
    "ObjectModelSquad",
    "ObjectModelTactic",
    "ObjectModelTransitionInstruction",
    "Player",
    "Squad",
    "SquadClubScreenshot",
    "SquadCleanupRecord",
    "SquadPlayerRecord",
    "SquadRecord",
    "SquadScreenshot",
    "SquadTacticApplication",
    "StructuredFormationSlot",
    "ScreenshotDerivedTacticDefinition",
    "StructuredTacticIssue",
    "StructuredTeamInstruction",
    "Tactic",
    "TacticDetailRecord",
    "TacticRecord",
    "TacticScreenshot",
]
