attributes:
  acceleration:
    abbreviation: Acc
    order: 1
  aggression:
    abbreviation: Agg
    order: 2
  agility:
    abbreviation: Agi
    order: 3
  aerial_reach:
    abbreviation: ARe
    order: 4
  anticipation:
    abbreviation: Ant
    order: 5
  balance:
    abbreviation: Bal
    order: 6
  communication:
    abbreviation: Com
    order: 7
  command_of_area:
    abbreviation: CoA
    order: 8
  composure:
    abbreviation: Com
    order: 9
  concentration:
    abbreviation: Cnt
    order: 10
  crossing:
    abbreviation: Cro
    order: 11
  decisions:
    abbreviation: Dec
    order: 12
  determination:
    abbreviation: Det
    order: 13
  dribbling:
    abbreviation: Dri
    order: 14
  eccentricity:
    abbreviation: Ecc
    order: 15
  finishing:
    abbreviation: Fin
    order: 16
  first_touch:
    abbreviation: Fir
    order: 17
  flair:
    abbreviation: Fla
    order: 18
  handling:
    abbreviation: Han
    order: 19
  heading:
    abbreviation: Hea
    order: 20
  jumping_reach:
    abbreviation: Jum
    order: 21
  leadership:
    abbreviation: Ldr
    order: 22
  long_shots:
    abbreviation: Lon
    order: 23
    active: false
  marking:
    abbreviation: Mar
    order: 24
  natural_fitness:
    abbreviation: Nat
    order: 25
  off_the_ball:
    abbreviation: OtB
    order: 26
  pace:
    abbreviation: Pac
    order: 27
  passing:
    abbreviation: Pas
    order: 28
  positioning:
    abbreviation: Pos
    order: 29
  reflexes:
    abbreviation: Ref
    order: 30
  stamina:
    abbreviation: Sta
    order: 31
  strength:
    abbreviation: Str
    order: 32
  tackling:
    abbreviation: Tck
    order: 33
  teamwork:
    abbreviation: Tea
    order: 34
  technique:
    abbreviation: Tec
    order: 35
  vision:
    abbreviation: Vis
    order: 36
  work_rate:
    abbreviation: Wor
    order: 37
  kicking:
    abbreviation: Kic
    order: 38
  one_on_ones:
    abbreviation: 1v1
    order: 39
  rushing_out:
    abbreviation: Rsh
    order: 40
  punching:
    abbreviation: Pun
    order: 41
  throwing:
    abbreviation: Thr
    order: 42
