version: 1

roles:
  ballPlayingGoalkeeper: [GK]
  sweeperKeeper: [GK]
  fullBack: [FB]
  wingBack: [WB]
  centreBack: [DC]
  ballPlayingCentreBack: [DC]
  deepLyingPlaymaker: [DM, MC]
  boxToBoxMidfielder: [DM, MC]
  defensiveMidfielder: [DM]
  pressingDefensiveMidfielder: [DM]
  wideMidfielder: [MW]
  winger: [MW, AMW]
  insideForward: [AMW]
  attackingMidfielder: [AMC]
  centreForward: [STC]
  targetForward: [STC]
  channelForward: [STC]
  trackingCentreForward: [STC]
  advancedPlaymaker: [MC, AMC]
  freeRole: [AMC]
  secondStriker: [AMC]
  channelMidfielder: [AMC]
  playmakingWinger: [MW, AMW]
  wideForward: [AMW]
  insideWinger: [AMW]
  deepLyingForward: [STC]
  poacher: [STC]
  falseNine: [STC]
  halfBack: [DM]
  droppingDefensiveMidfielder: [DM]
  trackingAttackingMidfielder: [AMC]
  trackingWideMidfielder: [MW]
  trackingWinger: [AMW]
