version: 1

duties:
  DEFEND: [defend, def, d]
  SUPPORT: [support, sup, s]
  ATTACK: [attack, att, a]
  AUTOMATIC: [automatic, auto]
  NONE: [none]

positions:
  GK: [goalkeeper]
  DR: [right defender, right back]
  DCR: [right centre back]
  DC: [centre back, central defender, d (c), d(c)]
  DCL: [left centre back]
  DL: [left defender, left back]
  WBR: [right wing back]
  DMCR: [right defensive midfielder]
  DM: [defensive midfielder]
  DMCL: [left defensive midfielder]
  WBL: [left wing back]
  MR: [right midfielder]
  MCR: [right central midfielder]
  MC: [central midfielder, m (c)]
  MCL: [left central midfielder]
  ML: [left midfielder]
  AMR: [right attacking midfielder]
  AMCR: [right central attacking midfielder]
  AMC: [attacking midfielder, am (c), am(c)]
  AMCL: [left central attacking midfielder]
  AML: [left attacking midfielder]
  STCR: [right striker]
  STC: [striker, centre forward]
  STCL: [left striker]

roles:
  ballPlayingGoalkeeper:
    displayName: Ball-Playing Goalkeeper
    abbreviations: [BPGK]
    aliases: [ball playing goalkeeper]
    positions: [GK]
    duties: [DEFEND, SUPPORT]
  sweeperKeeper:
    displayName: Sweeper Keeper
    abbreviations: [SK]
    aliases: [sweeper keeper]
    positions: [GK]
    duties: [DEFEND, SUPPORT, ATTACK]
  fullBack:
    displayName: Full-Back
    abbreviations: [FB]
    aliases: [full back]
    positions: [DR, DL]
    duties: [DEFEND, SUPPORT, ATTACK, AUTOMATIC]
  wingBack:
    displayName: Wing-Back
    abbreviations: [WB]
    aliases: [wing back]
    positions: [DR, DL, WBR, WBL]
    duties: [DEFEND, SUPPORT, ATTACK, AUTOMATIC]
  centreBack:
    displayName: Centre-Back
    abbreviations: [CB]
    aliases: [centre back, center back]
    positions: [DCR, DC, DCL]
    duties: [DEFEND]
  ballPlayingDefender:
    displayName: Ball-Playing Defender
    abbreviations: [BPD]
    aliases: [ball playing defender]
    positions: [DCR, DC, DCL]
    duties: [DEFEND]
  deepLyingPlaymaker:
    displayName: Deep-Lying Playmaker
    abbreviations: [DLP]
    aliases: [deep lying playmaker]
    positions: [DMCR, DM, DMCL, MCR, MC, MCL]
    duties: [DEFEND, SUPPORT]
  boxToBoxMidfielder:
    displayName: Box-to-Box Midfielder
    abbreviations: [BBM]
    aliases: [box to box midfielder]
    positions: [MCR, MC, MCL]
    duties: [SUPPORT]
  defensiveMidfielder:
    displayName: Defensive Midfielder
    abbreviations: [DM]
    aliases: [defensive midfielder]
    positions: [DMCR, DM, DMCL]
    duties: [DEFEND, SUPPORT]
  pressingDefensiveMidfielder:
    displayName: Pressing Defensive Midfielder
    abbreviations: [PDM]
    aliases: [pressing defensive midfielder]
    positions: [DMCR, DM, DMCL]
    duties: [DEFEND, SUPPORT]
  wideMidfielder:
    displayName: Wide Midfielder
    abbreviations: [WM]
    aliases: [wide midfielder]
    positions: [MR, ML]
    duties: [DEFEND, SUPPORT, ATTACK, AUTOMATIC]
  winger:
    displayName: Winger
    abbreviations: [W]
    aliases: [winger]
    positions: [MR, ML, AMR, AML]
    duties: [SUPPORT, ATTACK]
  insideForward:
    displayName: Inside Forward
    abbreviations: [IF]
    aliases: [inside forward]
    positions: [AMR, AML]
    duties: [SUPPORT, ATTACK]
  attackingMidfielder:
    displayName: Attacking Midfielder
    abbreviations: [AM]
    aliases: [attacking midfielder]
    positions: [AMCR, AMC, AMCL]
    duties: [SUPPORT, ATTACK]
  completeForward:
    displayName: Complete Forward
    abbreviations: [CF]
    aliases: [complete forward]
    positions: [STCR, STC, STCL]
    duties: [SUPPORT, ATTACK]
  targetForward:
    displayName: Target Forward
    abbreviations: [TF]
    aliases: [target forward]
    positions: [STCR, STC, STCL]
    duties: [SUPPORT, ATTACK]
  channelForward:
    displayName: Channel Forward
    abbreviations: [ChF]
    aliases: [channel forward]
    positions: [STCR, STC, STCL]
    duties: [SUPPORT, ATTACK]
  trackingCentreForward:
    displayName: Tracking Centre Forward
    abbreviations: [TCF]
    aliases: [tracking centre forward, tracking center forward]
    positions: [STCR, STC, STCL]
    duties: [SUPPORT, ATTACK]
  advancedPlaymaker:
    displayName: Advanced Playmaker
    abbreviations: [AP]
    aliases: [advanced playmaker]
    positions: [MCR, MC, MCL, AMCR, AMC, AMCL]
    duties: [SUPPORT, ATTACK]

instructions:
  inPossession:
    passingDirectness: [much shorter, shorter, standard, more direct, much more direct]
    tempo: [much lower, lower, standard, higher, much higher]
    timeWasting: [never, sometimes, frequently]
    attackingTransition: [hold shape, counter]
    attackingWidth: [very narrow, narrow, standard, wide, very wide]
    playForSetPieces: ['false', 'true']
    creativeFreedom: [be more disciplined, balanced, be more expressive]
    buildUpStrategy: [play out of defence]
    goalKicks: [short, mixed, long]
    goalkeeperDistribution: [centre backs, full backs, flanks, playmaker, target forward]
    supportingRuns: [underlap left, underlap right, overlap left, overlap right]
    dribbling: [dribble less, balanced, run at defence]
    progressThrough: [left, centre, right]
    passReception: [to feet, into space]
    patience: [work ball into box]
    shotsFromDistance: [shoot on sight]
    crossingStyle: [low, mixed, floated, whipped]
    goalkeeperDistributionSpeed: [slow pace down, distribute quickly]
  outOfPossession:
    lineOfEngagement: [low block, mid block, high press]
    defensiveLine: [much lower, lower, standard, higher, much higher]
    triggerPress: [much less often, less often, standard, more often, much more often]
    defensiveTransition: [regroup, counter press]
    tackling: [stay on feet, balanced, get stuck in]
    crossEngagement: [stop crosses, invite crosses]
    pressingTrap: [outside, inside]
    shortGoalkeeperDistribution: ['false', 'true']
    defensiveLineBehaviour: [drop off more, step up more]
